name: xlcdapp
description: "xlcdapp-笑裡藏道"
publish_to: 'none'
version: 0.8.1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  # Firebase packages
  #firebase_core: ^2.25.4
  #firebase_analytics: ^10.8.6
  #firebase_auth: ^4.17.4
  #cloud_firestore: ^4.15.5
  firebase_core: ^2.12.0
  firebase_analytics: ^10.4.0
  firebase_auth: ^4.6.0
  cloud_firestore: ^4.8.5

  url_launcher: ^6.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
  - assets/
