name: xlcdapp
description: "xlcdapp-笑裡藏道"
publish_to: 'none'
version: 1.2.1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  # Firebase
  cloud_firestore: ^6.1.0
  firebase_analytics: ^12.0.4
  firebase_auth: ^6.1.2
  firebase_core: ^4.2.1
  google_sign_in: ^6.2.1
  google_sign_in_dartio: ^0.3.0
  url_launcher: ^6.2.4
  web: ^1.1.1

  collection: ^1.17.0
  go_router: ^17.0.0
  path_to_regexp: ^0.4.0
  quiver: ^3.1.0
  #url_launcher: ^6.1.1
  url_strategy: ^0.3.0
  window_size:
    git:
      url: https://github.com/google/flutter-desktop-embedding.git
      path: plugins/window_size
  youtube_player_iframe: ^5.0.0
  logging: ^1.2.0
  flutter_adaptive_scaffold: ^0.3.3+1
  flutter_signin_button: ^2.0.0
  flutter_native_splash: ^2.4.0
  youtube_player_flutter: ^9.0.0
  flutter_inappwebview: ^6.0.0
  shared_preferences: ^2.2.3
  provider: ^6.1.2
  easy_localization: ^3.0.7
  package_info_plus: ^9.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.24.0

  flutter_lints: ^6.0.0

flutter_native_splash:
  color: "#E6EBEB" #light
  #color: "#241E30" #dark
  #image: "assets/logos/xlcd_splash_logo.gif"
  #image: "assets/logos/xlcd_splash_logo_apng.png"
  image: "assets/logos/xlcd_splash_logo.png"
  web_image_mode: center
  android_gravity: center
  ios_content_mode: center

flutter:
  uses-material-design: true

  assets:
  - assets/
  - assets/icons/
  - assets/photos/
  - assets/logos/
  - assets/translations/

dependency_overrides:
  win32: ^5.5.1
